version: "2"

services:

  db:
    image: mariadb
    ports:
    - "3307:3306"
    volumes:
    - .:/var/lib/mysql
    restart: always
    container_name : Alaya_de
    environment:
      MYSQL_ROOT_PASSWORD: root
